language: go
go:
    - 1.9

services:
  - docker

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=kapekto1/responder
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:0.1 .
  - docker tag $REPO:$TAG
  - docker tag $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO